### ISSUE TITLE
Feat: normalize whitespace in compiler frontmatter

### ISSUE THREAD

**Issue by drwpow** [withastro/compiler#10]
In the compiler’s generated code, it’ll export the frontmatter with `// ---` comments to show the boundaries:

```
// ---
your code…
your code…
// ---
component wrapper
```

However due to all the transformations, the whitespace surrounding `// ---` and within is very inconsistent from file to file. As a result, our tests are noisy, and we spend too much time as it is dealing with line break diffs that don’t matter.

As a cleanup task, let’s do some **bare minimum** work to make the compiler’s output a little more consistent, possibly with a cleanup pass.

Out of scope would be formatting / indenting your HTML perfectly. This isn’t so much about that, as simply cleaning up whitespace within the generated JS to make testing and output comparison a lot less noisy.

**Comment by natemoo-re** [comment]
This no longer happens!
