### ISSUE TITLE
🐛 BUG: `data-astro-reload` should accept value

### ISSUE THREAD

**Issue by stefanprobst** [withastro/compiler#1006]
### What version of `@astrojs/compiler` are you using?

2.8.0

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

i want to be able to conditionally apply the `data-astro-reload` attribute, i.e. `<a data-astro-reload={shouldReload || undefined}>`, but i get a warning that "The data-astro-reload attribute does not accept a value".

```ts
import { parse } from '@astrojs/compiler';

const result = await parse('<a data-astro-reload={undefined} href="#">Click</a>')

console.log(result.diagnostics)
```

```
[
  {
    severity: 2,
    code: 2005,
    location: { file: '<stdin>', line: 1, column: 23, length: 9 },
    hint: '',
    text: 'The data-astro-reload attribute does not accept a value'
  }
]
```

the warning is surfaced via `eslint-plugin-astro`'s `valid-compile` rule.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/stackblitz-starters-c53khs?file=index.js

**Comment by matthewp** [comment]
Closed by https://github.com/withastro/compiler/pull/1012
