### ISSUE TITLE
🐛 BUG: panic: Export statements must be placed at the top of .astro files!

### ISSUE THREAD

**Issue by lloydjatkinson** [withastro/compiler#195]
### What version of `astro` are you using?

0.21.6

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

Astro 0.21+ introduces a regression where `export` statements **must** be placed before `import` statements. Otherwise, the build will fail with `panic: Export statements must be placed at the top of .astro files!`.

Ideally this would not be a requirement as most conventional JS/TS places `import` in the very first lines.

### Link to Minimal Reproducible Example

https://astro.new

**Comment by lloydjatkinson** [comment]
Thanks for taking a look! 😀

**Comment by RafidMuhymin** [comment]
@natemoo-re More on the bug! This panic error is also shown if you are exporting interfaces inside your component and importing node built-ins at the same time. If you remove the import statements of every node built-in in the file the error goes away.

**Comment by natemoo-re** [comment]
So I've opened a PR to remove the `panic` when we find an export, but I'm not positive that will actually fix this issue... I'll have to test that branch against the repros here.

For reference: https://github.com/withastro/compiler/pull/344

**Comment by natemoo-re** [comment]
Exciting news! This is currently our oldest active issue, but there's a PR up that will remove this limitation. 🎉 https://github.com/withastro/compiler/pull/463
