### ISSUE TITLE
🐛 BUG: Can't perform maths using variables inside the JSX {} operator

### ISSUE THREAD

**Issue by RafidMuhymin** [withastro/compiler#221]
### What version of `@astrojs/compiler` are you using?

0.5.7

### What package manager are you using?

yarn

### What operating system are you using?

Ubuntu

### Describe the Bug

I am facing the following error when trying to set `(height * 100) / width` as the value of any attribute.

![image](https://user-images.githubusercontent.com/63650415/146058525-d5b406e1-dc0a-4336-b0d8-bb45c72df9af.png)

And this error when used inside an element,

![image](https://user-images.githubusercontent.com/63650415/146059707-ad3df589-82ef-401a-bd56-c7aea2f22651.png)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-hua66y?file=src%2Fpages%2Findex.astro

**Comment by TomSmedley** [comment]
Hello,

I don't know if this has been merged yet but I'm still having the issue. 
https://stackblitz.com/edit/github-azpgla?file=src/pages/index.astro
