### ISSUE TITLE
🐛 BUG: Components inside <noscript> are not parsed through the compiler

### ISSUE THREAD

**Issue by markpinero** [withastro/compiler#225]
### What version of `astro` are you using?

0.21.13

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Any components in a `<noscript>` tag only pass in the source code. It does not get parsed through the compiler.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-8nksfd?file=src/pages/index.astro

**Comment by moritzlaube** [comment]
Maybe it makes sense to allow the `is:raw` directive on the `noscript` element as well?
