### ISSUE TITLE
🐛 BUG: Nil pointer dereference when the file is long

### ISSUE THREAD

**Issue by jonathantneal** [withastro/compiler#255]
### What version of `@astrojs/compiler` are you using?

0.8.2

### What package manager are you using?

npm, yarn

### What operating system are you using?

Mac, Windows, Linux

### Describe the Bug

There’s an issue in the compiler that has something to do with the number of characters in a file.

Example: https://github.com/lloydjatkinson/going-insane

```
panic: runtime error: nil pointer dereference
RuntimeError: Error: Uh oh, the Astro compiler encountered an unrecoverable error!
```

- If we change the project from 4-space to 2-space or from 4-space to tabs, the error goes away.
- If we replace every character in a class with z it still throws.
- It has something to do with the number of characters in the file.

### Link to Minimal Reproducible Example

https://github.com/lloydjatkinson/going-insane

**Comment by natemoo-re** [comment]
Closing in favor of https://github.com/withastro/compiler/issues/256
