### ISSUE TITLE
🐛 BUG: scripts with a src prop and a prop with a value of true are hidden from the build output when using a js component

### ISSUE THREAD

**Issue by Mikkel-T** [withastro/compiler#266]
### What version of `astro` are you using?

latest

### What package manager are you using?

yarn

### What operating system are you using?

Windows

### Describe the Bug

Script tags with a src prop and a prop with either `"true"`, `true` or `{true}` as the value are hidden in the build output when using a js component in the page such as a react or svelte component.
Without having gone too deep into the technical side of astro, i suspect that the issue is with rendering scripts in the `SCRIPTS` array created by [this](https://github.com/withastro/compiler/blob/main/internal/printer/print-to-js.go#L199-L207) part of the compiler, it looks like scripts without a `src` prop that are passed into that array are all fine and get added to the last part of the head in the output file while scripts with a `src` prop never get added when a frontend framework is used in the page (More info [here](https://gist.github.com/Mikkel-T/5cadb66b94d9cf5d862a65eb0443308a))
I am sure that there is much more to this bug than I have been able to find, but it looks like one of the props have to be `src` while the other can be named whatever you want, just as long as it has one of the values mentioned above.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-icwr81?file=src%2Fpages%2Findex.astro&on=stackblitz

**Comment by natemoo-re** [comment]
I'm going to try to tackle this soon. Per https://github.com/withastro/rfcs/pull/41, any attribute other than `hoist` should mean a `<script>` tag remains on the page as authored.

**Comment by natemoo-re** [comment]
OK I think this has been addressed? In https://github.com/withastro/rfcs/blob/main/proposals/0016-style-script-defaults.md, we introduced the `is:inline` directive to opt scripts out of processing, meaning you should now have full control over which scripts are included literally in the page.
