### ISSUE TITLE
🐛 BUG: Self closing <i/> tags duplicate depending on the context

### ISSUE THREAD

**Issue by SnowJambi** [withastro/compiler#272]
### What version of `@astrojs/compiler` are you using?

0.9.2

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

When using a self closing `<i/>` tag, the tag duplicates for what seems to be each indentation level above itself. Using too many of these tags quickly results in a crash.

To see what is happening, right click > view frame source on the stackblitz to see the source html, or see the following code blocks

Input 

```astro
<body>
	<div class="div1">
		<div class="div2">
			<div class="div3">
				<i class='i1' />
			</div>
		</div>
	</div>

	<div class="div4">
		<div class="div5">
			<div class="div6">
				<i class='i2' />
			</div>
		</div>
	</div>

	<div class="div7">
		<div class="div8">
			<div class="div9">
				<i class='i3' />
			</div>
		</div>
	</div>

	<div class="div10">
		<div class="div11">
			<div class="div12">
				<i class='i4' />
			</div>
		</div>
	</div>

</body>
```

Output
```astro
<body>
	
	<div class="div1 astro-FUZDCGGA">
		<div class="div2 astro-FUZDCGGA">
			<div class="div3 astro-FUZDCGGA">
				<i class="i1 astro-FUZDCGGA"></i><i class="i1 astro-FUZDCGGA">
			</i></div><i class="i1 astro-FUZDCGGA">
		</i></div><i class="i1 astro-FUZDCGGA">
	</i></div><i class="i1 astro-FUZDCGGA">

	<div class="div4 astro-FUZDCGGA">
		<div class="div5 astro-FUZDCGGA">
			<div class="div6 astro-FUZDCGGA">
				<i class="i2 astro-FUZDCGGA"></i><i class="i2 astro-FUZDCGGA">
			</i></div><i class="i2 astro-FUZDCGGA">
		</i></div><i class="i2 astro-FUZDCGGA">
	</i></div><i class="i2 astro-FUZDCGGA">

	<div class="div7 astro-FUZDCGGA">
		<div class="div8 astro-FUZDCGGA">
			<div class="div9 astro-FUZDCGGA">
				<i class="i3 astro-FUZDCGGA"></i><i class="i3 astro-FUZDCGGA">
			</i></div><i class="i3 astro-FUZDCGGA">
		</i></div><i class="i3 astro-FUZDCGGA">
	</i></div><i class="i3 astro-FUZDCGGA">

	<div class="div10 astro-FUZDCGGA">
		<div class="div11 astro-FUZDCGGA">
			<div class="div12 astro-FUZDCGGA">
				<i class="i4 astro-FUZDCGGA"></i><i class="i4 astro-FUZDCGGA">
			</i></div><i class="i4 astro-FUZDCGGA">
		</i></div><i class="i4 astro-FUZDCGGA">
	</i></div><i class="i4 astro-FUZDCGGA">

	</i></i></i></i>
 </body>
```

### Link to Minimal Reproducible Example

https://stackblitz.com/github/snowjambi/i-tag-duplication?file=src%2Fpages%2Findex.astro

**Comment by SnowJambi** [comment]
Just some more information:

I have found that this is not only occurs with `<i>` tags, but many others as well. Not use cases that are likely to come up, but still.

I'm sure there a more but the ones I have come across are
`<i>, <a>, <b>, <s>, <u>, <tt>, <code>, <small>, <strong> <em>`
Notably they seem to almost all be related to text formatting.

**Comment by natemoo-re** [comment]
Thanks for opening an issue and for investigating this! You were right that this issue was happening because those particular elements have special handling since they are defined as "formatting elements". 

This behavior is fixed in https://github.com/withastro/compiler/pull/279.
