### ISSUE TITLE
🐛 BUG: memory access out of bounds with KaTeX

### ISSUE THREAD

**Issue by JuanM04** [withastro/compiler#277]
### What version of `astro` are you using?

0.22.19

### What package manager are you using?

npm, yarn

### What operating system are you using?

Linux

### Describe the Bug

When using markdown and installing `katex`, `remark-math` and `rehype-katex`, some math equations throws a wasm error: `memory access out of bounds`. Specifically, some functions like `\frac{1}{2}`, or `\sqrt[3]{27}` (interestingly, `\sqrt{4}` doesn't throw)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-vrzdws?file=src/pages/index.md

**Comment by JuanM04** [comment]
Thanks! I was just narrowing down where the bug happens until I've reached this minimal example: https://stackblitz.com/edit/node-ldbkbx?file=index.js

**Comment by JuanM04** [comment]
Thanks! I was just narrowing down where the bug happens until I've reached this minimal example: https://stackblitz.com/edit/node-ldbkbx?file=index.js

**Comment by natemoo-re** [comment]
Thanks for the amazing reproductions! I'm taking a look at this today ☺️

**Comment by JuanM04** [comment]
After seeing your PR I've made a workaround to the original plugin:

```js
import { visit } from "unist-util-visit"
import rehypeKatex from "rehype-katex"

export default () => {
  return (tree, ...args) => {
    rehypeKatex({
      macros: {
        "\\unit": "\\ \\text{#1}",
      },
    })(tree, ...args)

    visit(tree, "element", (node) => {
      const className = node.properties?.className || []

      if (className.includes("math")) {
        node.properties["data-astro-raw"] = true
      }
    })
  }
}

```

**Comment by JuanM04** [comment]
@natemoo-re The error persists after upgrading to 0.10.2. I've updated the reproduction
