### ISSUE TITLE
🐛 BUG: bus error 10... RuntimeError: memory access out of bounds

### ISSUE THREAD

**Issue by jladmore** [withastro/compiler#285]
### What version of `astro` are you using?

0.23.0-next.6

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

We are using alpine components embedded into the astro page. We have found after upgrading to 0.23.0-next.6 we get a bus error 10 on our Mac and RuntimeError: memory access out of bounds on stackblitz.

The issue relates to the size of the html block in an alpinejs template entity. If we make it smaller it works ok. If we use another astro component say CartItems.astro and include the block this way it works. When we have the full block between the template we get the error and crash..

There seems to be more information from the stackblitz runtime, than what we get from our Mac build.  

This works fine in 0.22.20

Thanks

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-nvdxee

**Comment by natemoo-re** [comment]
Confirming that #291 seems to fix this. See https://stackblitz.com/edit/withastro-astro-zd8qwj?file=package.json
