### ISSUE TITLE
🐛 BUG: Variables in markdown don't get picked up if standing alone in a line

### ISSUE THREAD

**Issue by schmackofant** [withastro/compiler#286]
### What version of `astro` are you using?

0.22.20

### What package manager are you using?

npm

### What operating system are you using?

macOS 12.1

### Describe the Bug

If you have a variable in the content of a .md file that is "alone" on a line, it doesn't get picked up by the compiler:

Works: `Do variables work: {frontmatter.value}`
Does not work: `{frontmatter.value}`

To reproduce you can look at the rendered content of this index.md page:
https://stackblitz.com/edit/github-5wquax?file=src/pages/posts/index.md

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-5wquax

**Comment by natemoo-re** [comment]
Hey @schmackofant! Sorry for the delay, but this was recently fixed (at least as recently as `astro@^1.0.0-beta.16`)

Here's a working [reproduction](https://stackblitz.com/edit/github-a5ht4v?file=src%2Fpages%2Findex.md)!
