### ISSUE TITLE
🐛 BUG: Component slots in markdown pages throw an error

### ISSUE THREAD

**Issue by tony-sull** [withastro/compiler#352]
### What version of `@astrojs/compiler` are you using?

0.14.1

### What package manager are you using?

pnpm

### What operating system are you using?

mac

### Describe the Bug

Ran into a build error when upgrading astro.build to astro@0.26.  Narrowed it down to component slots being used in two markdown pages

```html
<!-- src/pages/blog/introducing-astro.md -->
<Blockquote>
  <Fragment slot="quote">
    A well-designed system makes it easy to do the right things and annoying (but not impossible) to do the wrong things
  </Fragment>

  <Fragment slot="cite">Jeff Atwood, <a href="https://blog.codinghorror.com/falling-into-the-pit-of-success/">Falling Into The Pit of Success</a></Fragment>
</Blockquote>
```

**Error message**
```
panic: Element with a slot='...' attribute must be a child of a component or a descendant of a custom element

goroutine 124 [running]:
github.com/withastro/compiler/internal/printer.render1(0x5f9b08, 0x57f860, {0x0, 0x0, 0x3, 0x0, {{0x673e40, 0x8}, {0x4b05f0, 0x4f}, ...}})
	github.com/withastro/compiler/internal/printer/print-to-js.go:409 +0x533
```

### Link to Minimal Reproducible Example

https://github.com/withastro/astro.build/tree/chore/astro-0.26

**Comment by JuanM04** [comment]
It also happend to me with the slot being inside a conditional:

```astro
<MainLayout {...props}>
  <slot />

  {mathStyles && <link rel="stylesheet" href={mathStyles} slot="head" />}
</MainLayout>
```

**Comment by natemoo-re** [comment]
Ah that might be the culprit, @JuanM04! I probably won't be able to look at this for another week, but I'd really like to fix this ASAP.

**Comment by umbrellasystem404** [comment]
> ### What version of `@astrojs/compiler` are you using?
> 
> 0.14.1
> 
> ### What package manager are you using?
> 
> pnpm
> 
> ### What operating system are you using?
> 
> mac
> 
> ### Describe the Bug
> 
> Ran into a build error when upgrading astro.build to astro@0.26.  Narrowed it down to component slots being used in two markdown pages
> 
> ```html
> 
> <Blockquote>
>   <Fragment slot="quote">
>     A well-designed system makes it easy to do the right things and annoying (but not impossible) to do the wrong things
>   </Fragment>
> 
>   <Fragment slot="cite">Jeff Atwood, <a href="https://blog.codinghorror.com/falling-into-the-pit-of-success/">Falling Into The Pit of Success</a></Fragment>
> </Blockquote>
> ```
> 
> **Error message**
> ```
> panic: Element with a slot='...' attribute must be a child of a component or a descendant of a custom element
> 
> goroutine 124 [running]:
> github.com/withastro/compiler/internal/printer.render1(0x5f9b08, 0x57f860, {0x0, 0x0, 0x3, 0x0, {{0x673e40, 0x8}, {0x4b05f0, 0x4f}, ...}})
> 	github.com/withastro/compiler/internal/printer/print-to-js.go:409 +0x533
> ```
> 
> ### Link to Minimal Reproducible Example
> 
> https://github.com/withastro/astro.build/tree/chore/astro-0.26
