### ISSUE TITLE
🐛 BUG: `@astrojs/compiler` panic

### ISSUE THREAD

**Issue by jasikpark** [withastro/compiler#365]
%23%23%23 Describe the Bug
    
    `@astrojs/compiler` encountered an unrecoverable error when compiling the following file.
    
    **src/components/ConfigOption.astro**
    ```astro
    ---
import { Code, Markdown } from 'astro/components'

**Comment by jasikpark** [comment]
Attempting to run with 1.0-beta.5 results in the same error:

<img width="655" alt="image" src="https://user-images.githubusercontent.com/10626596/163858836-57f20d84-6e24-42ec-b7d4-213e95be9c1e.png">

**Comment by jasikpark** [comment]
@natemoo-re thx for looking into this!

**Comment by natemoo-re** [comment]
Hmm, yeah still seeing this issue. Going to try to fix it today!
