### ISSUE TITLE
🐛 BUG: Panic when importing type

### ISSUE THREAD

**Issue by IanVS** [withastro/compiler#378]
### What version of `@astrojs/compiler` are you using?

0.14.2

### What package manager are you using?

npm

### What operating system are you using?

mac

### Describe the Bug

I'm working on upgrading my app to 0.26, and was getting a confusing message about 

```
Parse failure: Unexpected character '!' (1:1)
Contents of line 1: #!/usr/bin/env node
Error: Parse failure: Unexpected character '!' (1:1)
Contents of line 1: #!/usr/bin/env node
    at ssrTransform (/Users/ianvs/code/defined/nebula-docs/node_modules/vite/dist/node/chunks/dep-88bd5805.js:54490:15)
    at doTransform (/Users/ianvs/code/defined/nebula-docs/node_modules/vite/dist/node/chunks/dep-88bd5805.js:55889:17)
```

I eventually traced it down to this line:

```ts
import type { MarkdownInstance } from 'astro';
```

Which, according to the [docs](https://docs.astro.build/en/guides/typescript/#type-imports), I think should be fine?  

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-3gexpj?file=src/pages/index.astro

**Comment by npup** [comment]
This happens in 1.0.0-beta.20 as well (and that's what is used in the linked reproduction, too)

**Comment by Hellrespawn** [comment]
I'm having the same issue. Specifically, it only happens if I import `MarkdownInstance` within an Astro or Svelte component, I can use it "safely" in separate `.ts`-files.
