### ISSUE TITLE
🐛 BUG: Cannot use bare slot and conditional content

### ISSUE THREAD

**Issue by IanVS** [withastro/compiler#379]
### What version of `@astrojs/compiler` are you using?

0.14.2

### What package manager are you using?

npm

### What operating system are you using?

mac

### Describe the Bug

During an upgrade to astro 0.26, I started getting an error from a component with a slot and some conditional markup rendered underneath it.  I've reproduced this in the 1.0.0 beta, and have a link below.

example:

```astro
---
const {description} = Astro.props;
---

<slot />
{description && <div>{description}</div>}
```
### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ahfzyt?file=src/Component.astro

**Comment by Jutanium** [comment]
This should be working now! [See the same example but with an updated Astro version](https://stackblitz.com/edit/github-ahfzyt-mklqrd?file=src%2FComponent.astro).
