### ISSUE TITLE
🐛 BUG: "\" in MD Setup: breaks build and dev

### ISSUE THREAD

**Issue by tusamni** [withastro/compiler#382]
### What version of `astro` are you using?

1.0.0-beta.19

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows 11

### Describe the Bug

I discovered a frustrating compiler issue.

In a random .MD file, I had an accidental "\" at the end of my layout import. This backslash causes dev to break and build hangs at `[build] Collecting build information...`

Here's the code:

```
setup: |
  import Layout from "@/layouts/PostLayout"\
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-c3xupu?file=src%2Fpages%2Fposts%2Findex.md&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
I'm going to close this as Astro Flavored Markdown has been deprecated to be officially removed in Astro 2.0.0. [Check out our Markdown guide](https://docs.astro.build/en/guides/markdown-content/) for the most up-to-date way to work with Markdown in Astro.
