### ISSUE TITLE
🐛 BUG: BaseHead component in head section is putting scripts into body

### ISSUE THREAD

**Issue by moritzlaube** [withastro/compiler#389]
### What version of `astro` are you using?

1.0.0-beta.27

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I have a BaseLayout component in which I am using a BaseHead component to pass my meta tags etc. Next to to that component I am using a named slot like to also Pass Social MEta Tags: 

```
// BaseLayout.astro
<html lang="en">
  <head>
    <BaseHead {title} {description} />
    <slot name="social" />
  </head>
  <body>
    <main>
      <slot />
    </main>
  </body>
</html>
```

I then have a BlogPost component which usees the BaseLayout component and passes a Social Meta component like so: 
```
<Layout {title} {description}>
  <SocialMeta slot="social" />
  <main>
    <h1>{title}</h1>
    <img src={headerImage} />
    <slot />
  </main>
</Layout>
```

This setup produces a weird issue where all my script tags from the BaseHead component are rendered into the body tag of the final html. This is an issue since early on (24 or so). I posted it on the Discord channel but never filed a bug report. 

Check out the Stackblitz. Run it and open the DevTools.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-akxdgm-wqfikb?file=src/layouts/BlogPost.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment]
I couldn't reproduce this using your reproduction @moritzlaube, I'm I missing something or you got rid of the issue?
