### ISSUE TITLE
🐛 BUG: Slots are not working for conditionally rendered Layouts

### ISSUE THREAD

**Issue by RafidMuhymin** [withastro/compiler#409]
### What version of `astro` are you using?

1.0.0-beta.31

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

If a Layout component is rendered conditionally and has content inside the body, instead of passing the content to the requested slot, Astro just pastes the content into the page.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-qsp9mn

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
After upgrading to the latest version of Astro, I was able to confirm that this works!

See https://stackblitz.com/edit/github-qsp9mn-ujodd4?file=src%2Fpages%2Findex.astro for a repro.
