### ISSUE TITLE
🐛 BUG: `.astro` parsing fails when multiple `return` statements are present

### ISSUE THREAD

**Issue by jon-loubert** [withastro/compiler#420]
### What version of `astro` are you using?

v1.0.0-beta.38

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

NPM

### What operating system are you using?

MacOS

### Describe the Bug

See the linked StackBlitz for a minimal example. The relevant parts that break the parsing: 
```astro
const test = ['a', 'b', 'c'];
---
{test.map(t => {
  if (t == 'a') {
    return (
      <Card href="https://docs.astro.build/" title="Test 1" body="..." /> 
    );
  } else if (t == 'b') {
    return (
      <Card href="https://docs.astro.build/" title="Test 2" body="..." /> 
    );
  }
})}
```
If you remove the `else if` block, the one card is rendered fine. If you re-write the if-else logic to instead use `&&` and `||` operators, or switch-case, it renders fine. It's something specifically about the combination of `if` branches and `return` that causes the issue.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-4wnthh?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Fixed by https://github.com/withastro/compiler/pull/456
