### ISSUE TITLE
🐛 BUG: Outputting text in astro components without a wrapper elements gets text duplicated

### ISSUE THREAD

**Issue by felixsanz** [withastro/compiler#421]
### What version of `astro` are you using?

v1.0.0-beta.40

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

If an astro component returns:

```
Text
```

output is: `TextText`

Doesn't happen when component returns:

```
<>Text<>
```

### Link to Minimal Reproducible Example

https://codesandbox.io/s/young-currying-f0ygdd?file=/src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by antonyfaris** [comment]
I can confirm this. Also gets outputted in the ast.

**Comment by natemoo-re** [comment]
This was fixed in https://github.com/withastro/compiler/pull/429, but I forgot to close this issue as well.

Thanks for the report!
