### ISSUE TITLE
🐛 BUG: Trouble parsing markdown file

### ISSUE THREAD

**Issue by puzzlepupil** [withastro/compiler#446]
### What version of `@astrojs/compiler` are you using?

1.0.0-beta.63

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

![image](https://user-images.githubusercontent.com/67280672/177531670-a7e9a99e-1b9e-454e-ad0d-45f1491a1327.png)

  ```
  [6:39: Failed to parse Markdown file "/home/projects/mklikxjow.github/src/pages/posts/index.md": Could not parse expression with acorn: Expecting Unicode escape sequence \uXXXX] {   reason: 'Could not parse expression with acorn: Expecting Unicode escape sequence \\uXXXX',
  ```
  
  I'm not sure what about my markdown file is throwing off the compiler. I haven't noticed anything wrong on my end so I just wanted to submit this issue incase this is a bug on the compiler side.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-u3f66p?file=src/pages/posts/index.md

**Comment by ran-dall** [comment]
@poutingemoji The problem in this instance mate is that you can't run JS math functions in `{}`. You can retrieve the values as `{frontmatter.value}` but the actual math function will not function like this.

**Comment by natemoo-re** [comment]
I'm going to close this as Astro Flavored Markdown has been deprecated to be officially removed in Astro 2.0.0. [Check out our Markdown guide](https://docs.astro.build/en/guides/markdown-content/) for the most up-to-date way to work with Markdown in Astro.
