### ISSUE TITLE
🛠 Refactor: `p.printQuoted`

### ISSUE THREAD

**Issue by ran-dall** [withastro/compiler#480]
### What version of `@astrojs/compiler` are you using?

1.0.0-beta72

### What package manager are you using?

pnpm

### What operating system are you using?

Linux (Gentoo)

### Describe the Bug

In a recent conversation with @natemoo-re, it was discussed that `p.printQuoted` could benefit from a refactor.

### Link to Minimal Reproducible Example

N/A

**Comment by MoustaphaDev** [comment]
Hey @ran-dall 👋 Are you still planning to work on this?

**Comment by Princesseuh** [comment]
Closing since there's nothing actionable here, I can't find the context on this and some of the actors here are no longer active.
