### ISSUE TITLE
🐛 BUG: TSX output could type `Astro.props` automatically

### ISSUE THREAD

**Issue by Princesseuh** [withastro/compiler#499]
### What version of `@astrojs/compiler` are you using?

N/A

### What package manager are you using?

N/A

### What operating system are you using?

N/A

### Describe the Bug

It'd be great if the TSX output would automatically type `Astro.props` with the types from the user's Props interface. This is a feature we always wanted to do and it's finally possible, so why not

Something like 

`declare const Astro: { props: Props } & Omit<import('astro').AstroGlobal, 'props'>`

In the file should do the trick. It does create a weird Go To Definition behaviour, but GTD's behaviour on the Astro global is already weird because it goes into `env.d.ts` and not `astro.d.ts` like you'd expect. That's something we could fix in the language server manually or make it point to the Props interface etc

(Mainly making an issue for myself to remember, I can implement this)

### Link to Minimal Reproducible Example

N/A

**Comment by natemoo-re** [comment]
Note: #518 did NOT implement this, I was mistaken. Definitely something we can add, though.
