### ISSUE TITLE
🐛 BUG: `.astro` function hooks throw error despite valid JS syntax

### ISSUE THREAD

**Issue by Enteleform** [withastro/compiler#512]
### What version of `astro` are you using?

1.1.6

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

# Error
```
[getStaticPaths] getStaticPaths() function is required.
Make sure that you `export` a `getStaticPaths` function from your dynamic route.
Alternatively, set `output: "server"` in your Astro config file to switch to a non-static server build.
```

# Pages/Dynamic/[Route].astro
```astro
---
//###  [Works] Opening Bracket On Same Line  ###//
// export function getStaticPaths(){
//   return [{params:{Route:"Foo"}}]
// }

//###  [Error] Opening Bracket On Next Line  ###//
export function getStaticPaths()
  {return [{params:{Route:"Foo"}}]}

const {Route} = Astro.params
---


<h1>{Route}</h1>
```

# Notes

I just verified that this syntax works without issue in an another project of mine that is using Astro `1.0.0-beta.28`, so it seems that the bug has been introduced since then.

### Link to Minimal Reproducible Example

- https://stackblitz.com/edit/github-4kp4qh?file=src%2Fpages%2FDynamic%2F[Route].astro
- navigate to `/Dynamic/Foo` to reproduce.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Closed by https://github.com/withastro/compiler/pull/523
