### ISSUE TITLE
🐛 BUG: [TSX] Sourcemap and output issues

### ISSUE THREAD

**Issue by Princesseuh** [withastro/compiler#563]
### What version of `@astrojs/compiler` are you using?

0.27.0

### What package manager are you using?

pnpm

### What operating system are you using?

macOS

### Describe the Bug

The TSX output is very close, but it still has a few errors:

# Output

## Unclosed tags generate a weird output
```astro
---
const myMarkdown = await import('../content/post.md');
---

<myMarkdown.
```

```js
const myMarkdown = await import('../content/post.md');

<Fragment>
<
></
>
</Fragment>
export default function NpmImports__AstroComponent_(_props: Record<string, any>): any {}
```

I'd expect it to generate something like:

```html
<Fragment>
<myMarkdown.
</Fragment>
```

## Semicolons

The semi-colon handling is really good, but it turns out that it fails in a very common case:

```astro
---
const { hello } = Astro.props
---

<div class={hello}></div>
```

I am not sure at this time what the best heuristic is for this, I think for now maybe doing again what the previous implement did (so `"";` after the frontmatter) is best?

# Sourcemap

## Windows 

Mapping seems to be off on Windows, this cause [the `language-server`'s test suite to fail](https://github.com/withastro/language-tools/actions/runs/3200193024/jobs/5226809047)

## Attributes are weirdly mapped

Seems like the `"` is considered part of the ending tag? Also the first `"` maps to both quotes

```astro
---
---

<div class=""></div>
```

<img width="920" alt="image" src="https://user-images.githubusercontent.com/3019731/195395484-b310f320-7d51-4029-9664-c05317c662e8.png">

[Link to visualization](https://evanw.github.io/source-map-visualization/#NzQ0AAoKPEZyYWdtZW50Pgo8ZGl2IGNsYXNzPSIiPjwvZGl2PgoKPC9GcmFnbWVudD4KZXhwb3J0IGRlZmF1bHQgZnVuY3Rpb24gTnBtSW1wb3J0c19fQXN0cm9Db21wb25lbnRfKF9wcm9wczogUmVjb3JkPHN0cmluZywgYW55Pik6IGFueSB7fQovLyMgc291cmNlTWFwcGluZ1VSTD1kYXRhOmFwcGxpY2F0aW9uL2pzb247Y2hhcnNldD11dGYtODtiYXNlNjQsZXdvZ0lDSjJaWEp6YVc5dUlqb2dNeXdLSUNBaWMyOTFjbU5sY3lJNklGc2labWxzWlRvdkx5OVZjMlZ5Y3k5bGNtbHJZUzlRY205cVpXTjBjeTloYzNSeWJ5MXNZVzVuZFdGblpYTmxjblpsY2kxMFpYTjBMM055WXk5d1lXZGxjeTl1Y0cxSmJYQnZjblJ6TG1GemRISnZJaXdnSW1GemRISnZPbkoxYm5ScGJXVWlYU3dLSUNBaWMyOTFjbU5sYzBOdmJuUmxiblFpT2lCYklpMHRMVnh1TFMwdFhHNWNibHgxTURBelkyUnBkaUJqYkdGemN6MWNJbHdpWEhVd01ETmxYSFV3TUROakwyUnBkbHgxTURBelpWeHVJaXdnSWxCc1pXRnpaU0J2Y0dWdUlHRnVJR2x6YzNWbE9pQm9kSFJ3Y3pvdkwyRnpkSEp2TG1KMWFXeGtMMmx6YzNWbGN5SmRMQW9nSUNKdFlYQndhVzVuY3lJNklDSkJRVUZCTEVGQlFVYzdRVUZEU0N4QlFVRkhMRUZEUkVnN1FVRkJRVHRCUkVkQkxFTkJRVU1zUjBGQlJ5eERRVUZETEV0QlFVc3NRMEZCUXl4RlFVRkRMRUZCUVVNc1EwRkJReXhGUVVGRkxFZEJRVWNzUTBGQlF6dEJRVU53UWl4QlEwcEJPMEZCUVVFN0lpd0tJQ0FpYm1GdFpYTWlPaUJiWFFwOTQwOAB7CiAgInZlcnNpb24iOiAzLAogICJzb3VyY2VzIjogWyJmaWxlOi8vL1VzZXJzL2VyaWthL1Byb2plY3RzL2FzdHJvLWxhbmd1YWdlc2VydmVyLXRlc3Qvc3JjL3BhZ2VzL25wbUltcG9ydHMuYXN0cm8iLCAiYXN0cm86cnVudGltZSJdLAogICJzb3VyY2VzQ29udGVudCI6IFsiLS0tXG4tLS1cblxuXHUwMDNjZGl2IGNsYXNzPVwiXCJcdTAwM2VcdTAwM2MvZGl2XHUwMDNlXG4iLCAiUGxlYXNlIG9wZW4gYW4gaXNzdWU6IGh0dHBzOi8vYXN0cm8uYnVpbGQvaXNzdWVzIl0sCiAgIm1hcHBpbmdzIjogIkFBQUEsQUFBRztBQUNILEFBQUcsQUNESDtBQUFBO0FER0EsQ0FBQyxHQUFHLENBQUMsS0FBSyxDQUFDLEVBQUMsQUFBQyxDQUFDLEVBQUUsR0FBRyxDQUFDO0FBQ3BCLEFDSkE7QUFBQTsiLAogICJuYW1lcyI6IFtdCn0=)

### Link to Minimal Reproducible Example

N/A

**Comment by natemoo-re** [comment]
Going to close this as these particular issues have been addressed!
