### ISSUE TITLE
🐛 BUG: `@astrojs/compiler` panic

### ISSUE THREAD

**Issue by sugarmaplemedia** [withastro/compiler#566]
### What version of `astro` are you using?

1.4.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

I am trying to create a component that generates a number of columns equal to the amount specified in props. I cannot seem to use a for loop with Astro's inline JS syntax, so I generated a garbage array to "map" (loop) and build each column. The compiler crashes when I try to dynamically generate slot elements.

`@astrojs/compiler` encountered an unrecoverable error when compiling the following file.

**C:/Users/Harry/OneDrive/Desktop/git/website/src/components/Columns.astro**
```astro
---
const {amount} = Astro.props;
const colArr = [];
for (let i = 0; i < amount; i++) {
    colArr.push(amount.toString());
}
---

<section>
    { colArr.map((number) => (<div><slot name={"col-" + number} /></div>)) }
</section>
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-whlbtj?file=src/components/Columns.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
As @matthewp shared here https://github.com/withastro/astro/issues/5066#issuecomment-1277998365, Astro can only support dynamic slot names in some cases due to the compiler's limitations of static analysis.

Dynamic slot names inside of expressions are not supported, but we shouldn't `panic` in this case. I'll try to work on a fix that surfaces a more helpful warning.

**Comment by sugarmaplemedia** [comment]
Thank you @natemoo-re! I appreciate the update.

**Comment by Princesseuh** [comment]
This is not a panic anymore. There is now a (more or less) proper error message when that happens.
