### ISSUE TITLE
🐛 BUG: Related to #5447

### ISSUE THREAD

**Issue by wulinsheng123** [withastro/compiler#656]
### What version of `@astrojs/compiler` are you using?

last

### What package manager are you using?

pnpm

### What operating system are you using?

mac

### Describe the Bug

relate to #5447

### Link to Minimal Reproducible Example

https://github.com/crutchcorn/astro-props-spread-style-bug

**Comment by bluwy** [comment]
Tracking this in https://github.com/withastro/compiler/issues/659
