### ISSUE TITLE
🐛 BUG: [AST] Style tags get merged into html tag in certain situations

### ISSUE THREAD

**Issue by Princesseuh** [withastro/compiler#712]
### What version of `@astrojs/compiler` are you using?

1.0.1

### What package manager are you using?

pnpm

### What operating system are you using?

macOS

### Describe the Bug

In some cases, style tags gets merged into `html`. It seems to depends on the content of `head`, normal content works, but having a component there cause an issue. Cause the following issue in the Prettier plugin: https://github.com/withastro/prettier-plugin-astro/issues/316

Minimum repro:
```astro
<html lang="en">
<head>
    <BaseHead />
</head>
</html>

<style>
    @use "../styles/global.scss";
</style>
```

gets formatted into:

```astro
<html lang="en">
  <head>
    <BaseHead />
  </head>
  <style>
    @use "../styles/global.scss";
  </style>
</html>

```

Result AST: https://gist.github.com/Princesseuh/7ac0827647d2ff540a7bcadc7e8c11dc

### Link to Minimal Reproducible Example

See description

**Comment by HummingMind** [comment]
+1. Same issue.
Since I have "format on save" emabled, this happens every single save of the main layout. I almost checked it into source control that way once. 😢 

Hoping for a fix soon! 🍻 
Thank you!

**Comment by mks-h** [comment]
At least in my codebase, this issue doesn't break anything. I just let it be, and commit the way it is.

**Comment by chankruze** [comment]
It's still happening

**Comment by cprcrack** [comment]
Is there a workaround for this? It's incredibly annoying...

**Comment by cprcrack** [comment]
Same thing happens with <script> tags by the way, they get moved to the <body>

**Comment by paidge** [comment]
Hi and happy new year. I met the same problem. For a workaround, I disable Autosave during the edition of the file

**Comment by yudai-nkt** [comment]
> In some cases, style tags gets merged into `html`. It seems to depends on the content of `head`, normal content works, but having a component there cause an issue.

It looks like we can reproduce this without `<head>` element involved. Below is a reproduction taken from withastro/prettier-plugin-astro#408, where I've mistakenly submitted a duplicate:

```astro
import { format } from "prettier";

const source = `
---
---
<div>
</div>
<style>
</style>
`;

console.log(
  await format(source, { parser: "astro", plugins: ["prettier-plugin-astro"] })
);

console.log(
  await format(source.replace("div", "html"), {
    parser: "astro",
    plugins: ["prettier-plugin-astro"],
  })
);
```

I hope this smaller reproduction helps troubleshooting the problem.
