### ISSUE TITLE
🐛 BUG: Styling an emoji - runtime error: index out of range [11] with length 11

### ISSUE THREAD

**Issue by tysian** [withastro/compiler#733]
### What version of `@astrojs/compiler` are you using?

2.0.14

### What package manager are you using?

npm, pnpm

### What operating system are you using?

Windows 10

### Describe the Bug

Hello!

When I'm using `<style></style>` with `lang=scss`, I'm getting an runtime error.
I've noticed that my div has an cookie emoji 🍪 in it, and this was a reason why I was gettin a compiler error. Reproduced bug in stackblitz example.

![image](https://user-images.githubusercontent.com/16374473/220410444-90fcbf48-ab47-4e05-b8c0-7727abdd8e5e.png)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ze3pye?file=src/CookieBar.astro

**Comment by jasikpark** [comment]
this bug gives me https://fasterthanli.me/articles/the-bottom-emoji-breaks-rust-analyzer energy 😅

**Comment by tasuren** [comment]
As shown as below, not limited to emojis, this seems to happen if html tag has class and a few multibyte characters and also use style.
```astro
<style>a { font-size: 16px; }</style>
<a class="test">ツ</a>
```
It also seems to be possible to build, though not a radical solution, by assigning a character to a constant and using that constant to embed the character in an HTML tag:
```astro
---
const TSU = "ツ";
---
<style>a { font-size: 16px; }</style>
<a class="test">{TSU}</a>
```
Note that in some cases, it seems to work just by doing something like `{"ツ"}` even if you don't put it in a constant.
