### ISSUE TITLE
JSX is being rendered as raw data

### ISSUE THREAD

**Issue by djmtype** [withastro/compiler#757]
### What version of `astro` are you using?

2.1.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome, Firefox

### Describe the Bug

I updated my packages. Although, I was still running Astro 2.1.3, this had updated Astro's compiler. 
Given the example below, it seems when a component is self-closing and within a `map`, `{profile.service}` is literally rendered as `{profile.service}` instead of its value. 
A workaround is to either close the component with `</Icon>` or wrap the jsx logic within an html tag like `<span>`. 
```js
<Icon
class="profile__icon"
name={profile.icon}
width={24}
fill="currentColor" />
{profile.service}
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-4gqksw?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by space-otter** [comment]
It is related to #755.
An actual workaround is to downgrade the compiler to 1.2.0.
