### ISSUE TITLE
❗️🐛 Cannot read properties of undefined (reading 'toString') 

### ISSUE THREAD

**Issue by J-env** [withastro/compiler#758]
### What version of `astro` are you using?

2.1.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm,pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug
`npm run dev` or `npm run build`

It seems that an error will be reported only in the loop.

<img width="882" alt="image" src="https://user-images.githubusercontent.com/25259920/225284250-b1f7a2ac-ac35-4e4e-8891-4f0a24c3c4a6.png">

If no error occurs it will be like this:
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/25259920/225285468-982404bf-3b64-4ef3-bcb7-b755d53f42ee.png">

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-sdeict-bgq4ea?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Yep, confirmed that updating to the latest version of `@astrojs/compiler` fixes this. Might need to wipe you `package-lock.json` file just to be safe.
