### ISSUE TITLE
🐛 BUG: it didn't compress totally the content of the index.html file .

### ISSUE THREAD

**Issue by wulinsheng123** [withastro/compiler#766]
### What version of `@astrojs/compiler` are you using?

last

### What package manager are you using?

pnpm

### What operating system are you using?

mac

### Describe the Bug

![image](https://user-images.githubusercontent.com/27261522/229042810-95504282-d085-4987-872f-2bdc66c3bc40.png)
it didn't compress the content of the index.html file totally.

### Link to Minimal Reproducible Example

https://github.com/withastro/roadmap/issues/537

**Comment by ematipico** [comment]
What's the actual bug??

**Comment by wulinsheng123** [comment]
> What's the actual bug?? Could you please give a good title and maybe some description?

Please see the image I sent.
I think there is only one line in the image.

**Comment by natemoo-re** [comment]
I think this is because DOCTYPE is injected outside of the compiler?

Also just a heads up that this compression mode will not always result in a file that is a single line. There are situations where portions of the page won't be compressed (mainly inside of framework components to avoid hydration mismatches).

**Comment by wulinsheng123** [comment]
> I think this is because DOCTYPE is injected outside of the compiler?
> 
> Also just a heads up that this compression mode will not always result in a file that is a single line. There are situations where portions of the page won't be compressed (mainly inside of framework components to avoid hydration mismatches).

https://github.com/wulinsheng123/astro/blob/c85a4b0e60ea136fee7f6831c7ccd1fb4a6128ec/packages/astro/test/fixtures/minification-html/src/pages/index.astro#L4
![image](https://user-images.githubusercontent.com/27261522/229662899-75d32fc3-783d-4e53-a6a4-0feb4adc1b47.png)
there is only a pure template.

**Comment by wulinsheng123** [comment]
I found it occurs in Astro So I close it
