### ISSUE TITLE
🐛 BUG: You can't iterate with .map in an Astro component

### ISSUE THREAD

**Issue by rxtsel** [withastro/compiler#767]
### What version of `@astrojs/compiler` are you using?

2.1.8

### What package manager are you using?

pnpm

### What operating system are you using?

WSL Ubuntu 22-04

### Describe the Bug

I am receiving this error, I don't understand why the code is correct.

![image](https://user-images.githubusercontent.com/85462420/229178553-2fcb7208-6eb6-46cd-ba55-47de17d13d1a.png)

this is the code:

![image](https://user-images.githubusercontent.com/85462420/229178616-530c7c81-39f6-4ee7-a208-4c752d41790c.png)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-fzxb6h?file=src/components/SwiperHero.astro

**Comment by ematipico** [comment]
I just narrowed down you example to this

```json
---
import data from "../tmp/slider-hero.json"
---

<div class="swiper mySwiper-hero">
  <div class="swiper-wrapper">
   {
     data.map(({ title }) => {
       return <div>{title}</div>
     })
   }
  </div>
</div>
```

And it works! The issue is in your code :)

**Comment by ematipico** [comment]
Nvm, it seems the issue is something else...

**Comment by rxtsel** [comment]
> I just narrowed down your example to this:
> 
> ```gfm
> ---
> import data from "../tmp/slider-hero.json"
> ---
> 
> <div class="swiper mySwiper-hero">
>   <div class="swiper-wrapper">
>    {
>      data.map(({ title }) => {
>        return <div>{title}</div>
>      })
>    }
>   </div>
> </div>
> ```
> 
> And it works! The issue is in your code :)

Yes, if I remove some lines it works, that's the problem. As it is, it should work.

**Comment by ematipico** [comment]
@rxtsel I investigated the issue, and the problem is the HTML of the code.

The Astro compiler tries to be HTML compliant, so if there's invalid HTML, it will emit incorrect code - like in this case.

In your case you're emitting two nested anchor elements - `a > a`, which is not a valid HTML. On the other hand, we're aware that Astro doesn't emit any warnings for invalid HTML, which we plan to add in the near future.

**Comment by rxtsel** [comment]
Oh, I understand, thank you! 👊🏾
