### ISSUE TITLE
🐛 BUG: Conditional operator to declare an attribute to an HTML element

### ISSUE THREAD

**Issue by alex-nowicki** [withastro/compiler#769]
### What version of `@astrojs/compiler` are you using?

2.1.7

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

Unable to use a Conditional Operator to declare an attribute to an HTML element.

Given this example:

```
---
let show = true;

let showObj = {}

if (show) {
 showObj.hidden = ''
}

---

<p {show ? '' : 'hidden'}>This doesn't work</p>
<p {...showObj}>This works</p>

```

The HTML output is:

```
<p show="" ?="" ''="" :="" 'hidden'="">Conditionally hidden text</p>
<p hidden="">Conditionally hidden text</p>
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-1lm6up?file=src/pages/index.astro

**Comment by MoustaphaDev** [comment]
Using the shorthand syntax like this is not supported.
This is the syntax you might want to use
```astro
<p hidden={show ? null :true}>This doesn't work</p>
```

**Comment by alex-nowicki** [comment]
Good to know. I didn't spot that limitation in the documentation. Thanks for the alternative solution.

**Comment by MoustaphaDev** [comment]
No problem, closing this as it's just not valid syntax
