### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by Burleigh-Beach-Designs** [withastro/compiler#776]
### What version of `@astrojs/compiler` are you using?

2.3.0

### What package manager are you using?

npm

### What operating system are you using?

11

### Describe the Bug

CompilerError
Unknown compiler error.
runtime error: index out of range [0] with length 0
[See Docs Reference](https://docs.astro.build/en/reference/errors/compiler-error/)
This is almost always a problem with the Astro compiler, not your code. Please open an issue at https://astro.build/issues/compiler.
layouts/MainLayout.astro

---
import MainHead from "./MainHead.astro";
---

<MainHead title={title} description={description} />
<html lang="en">
	<body>
		<slot />
	</body>
</html>

Stack Trace
goroutine 8 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x6
github.com/withastro/compiler/internal_wasm/utils.ErrorToJSError(0x47a5a0, {0xb08898, 0x486150})
	github.com/withastro/compiler/internal_wasm/utils/utils.go:68 +0x2
main.Transform.func1.1.1.1()
	./astro-wasm.go:278 +0x5
panic({0x2daa0, 0x486150})
	runtime/panic.go:884 +0x29
github.com/withastro/compiler/internal.inBodyIM(0x47a6c0)
	github.com/withastro/compiler/internal/parser.go:1157 +0x658
github.com/withastro/compiler/internal.(*parser).parseCurrentToken(0x47a6c0)
	github.com/withastro/compiler/internal/parser.go:2966 +0x13
github.com/withastro/compiler/internal.(*parser).parse(0x47a6c0)
	github.com/withastro/compiler/internal/parser.go:2993 +0x3
github.com/withastro/compiler/internal.ParseWithOptions({0x7aaa8, 0x42c1e0}, {0x439af0, 0x1, 0x1})
	github.com/withastro/compiler/internal/parser.go:3057 +0x1c
main.Transform.func1.1.1()
	./astro-wasm.go:283 +0xe
created by main.Transform.func1.1
	./astro-wasm.go:274 +0x16

### Link to Minimal Reproducible Example

https:

**Comment by Burleigh-Beach-Designs** [comment]
ss

**Comment by Burleigh-Beach-Designs** [comment]
ss

**Comment by MoustaphaDev** [comment]
Closing as this was fixed in #891 🥳
