### ISSUE TITLE
Astro misparses table HTML

### ISSUE THREAD

**Issue by mb21** [withastro/compiler#870]
### Astro Info

```block
Astro                    v3.1.4
Node                     v16.20.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

The Astro template

```jsx
<table>
    <tr><td>{'foo'}</td></tr>
</table>
<h2>Chats</h2>
```

is misparsed and emits the HTML:

```jsx
<table>
  <tr><td>foo</td></tr>
  <h2>Chats</h2>
</table>
````

which is clearly invalid and not intended.

Browsers parse this as "Chats" appearing above the table containing "foo", instead of below.

### What's the expected result?

Output HTML corresponds to the input HTML.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ewybuh?file=src%2Fpages%2Findex.astro

**Comment by mb21** [comment]
Interestingly, closing the table twice (`</table></table>`) works 🤷

**Comment by bluwy** [comment]
NOTE: https://github.com/withastro/astro/issues/8765 reported a similar issue where the `table` markup at the top of the file is affecting the lower `form` markup generated.

**Comment by bluwy** [comment]
Re-opening since it was reverted in https://github.com/withastro/compiler/pull/889. Going to continue finding a fix

**Comment by MoustaphaDev** [comment]
From your comment in the other issue, I'd assume it's okay if I take this one too @bluwy
