### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by CH19** [withastro/compiler#900]
### What version of `@astrojs/compiler` are you using?

3.6.1

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

![AstroProblems](https://github.com/withastro/compiler/assets/111191916/4e1ff381-d2c4-45e8-b8b7-bf9a8452d65c)
![AstroProblems2](https://github.com/withastro/compiler/assets/111191916/743dbaae-abe6-4ee3-bf24-f9161231c351)

### Link to Minimal Reproducible Example

idk

**Comment by MoustaphaDev** [comment]
Hey @CH19! Could you provide a reproduction of the issue? You can create one from the [minimal starter](https://astro.new/minimal?on=stackblitz)

**Comment by MoustaphaDev** [comment]
I'm gonna close it for now, feel free to reopen when you can provide a reproduction.
