### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by jaimeviloriogreen** [withastro/compiler#912]
### What version of `@astrojs/compiler` are you using?

@astrojs+compiler@2.3.4

### What package manager are you using?

pnpm

### What operating system are you using?

mac

### Describe the Bug

ENOENT: no such file or directory, open '[userpath]/node_modules/.pnpm/@astrojs+compiler@2.3.4/node_modules/@astrojs/compiler/dist/astro.wasm'

Hint:
    This is almost always a problem with the Astro compiler, not your code. 

### Link to Minimal Reproducible Example

https://astro.new

**Comment by jaimeviloriogreen** [comment]
this issue happened later i installed @astrojs/vue.

**Comment by MoustaphaDev** [comment]
Hello 👋
I wasn't able to reproduce it by just installing the vue integration.
Without a proper reproduction, we can really debug the issue. Please add a reproduction

**Comment by MoustaphaDev** [comment]
I'll close this for now, feel free to reopen when you can provide a reproduction
